adding classification result
BuildForSDGCohort2/Team-236-Group-A-backend pull request #10
Opened 2020-09-20 13:06 UTC by Wisdom0063

Adding classification data for retraining of model

2020-09-20 14:59 UTC, narteysarso requested changes
Can we resolve the Codacy quality PR

2020-09-20 14:59 UTC, narteysarso commented on src/middleware/authenticate.js
> +      message = "No authentication token provided";
Preceding this line with let keyword to declare message variable will resolve Codacy Quality PR

2020-09-22 14:07 UTC, narteysarso approved these changes
Awesome

2020-09-23 06:02 UTC, mickeymond approved these changes
great

2020-09-23 06:02 UTC, merged